services:
  - type: web
    name: consulta-regime-tributario
    env: python
    buildCommand: "./build.sh"
    startCommand: "PYTHONPATH=api ./venv/bin/python3 -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
